FROM ubuntu
LABEL   Version = "1.3"
LABEL   Descripcion = "Imagen Ubuntu con nginx, php y git"
LABEL   Autor = "Eduardo Lobo"
#ENV DIR1 /home/ubuntu/images_docker/ubuntu_files/
#ENV DIR2 /etc/nginx/sites-available/
RUN \
        apt-get update && \
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN \
        apt-get install -y software-properties-common && \
        add-apt-repository ppa:ondrej/php && \
        apt-get install -y php7.4 php-fpm && \
        update-alternatives --set php /usr/bin/php7.4 && \
        apt-get install -y nginx nano git && \
#		/etc/init.d/php7.4-fpm start && \
		echo "<?php phpinfo(); ?>" > /var/www/html/info.php
# COPY $DIR1/default $DIR2/default		

CMD /usr/sbin/nginx -g "daemon off;"


#Forma de correrla una vez construida
#docker run -d --name nginx_UBUNTU -p 80:80 ubuntu:nginx_php